package com.avito.android.remote.parse.adapter;

import com.avito.android.remote.model.category_parameters.AutoGeneratedValue;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonToken;
import java.io.IOException;
import kotlin.Metadata;
import kotlin.jvm.internal.s0;

/* compiled from: ParameterAttributeTypeAdapter.kt */
@s0
@Metadata(d1 = {"\u0000\u0010\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\u0007¢\u0006\u0004\b\u0003\u0010\u0004¨\u0006\u0005"}, d2 = {"Lcom/avito/android/remote/parse/adapter/ParameterAttributeTypeAdapter;", "Lcom/google/gson/TypeAdapter;", "Lcom/avito/android/remote/model/category_parameters/AutoGeneratedValue$Attribute;", "<init>", "()V", "_avito-discouraged_api-models_models"}, k = 1, mv = {1, 9, 0}, xi = 48)
/* loaded from: classes11.dex */
public final class ParameterAttributeTypeAdapter extends TypeAdapter<AutoGeneratedValue.Attribute> {
    /* JADX WARN: Failed to restore switch over string. Please report as a decompilation issue
    java.lang.NullPointerException
     */
    @Override // com.google.gson.TypeAdapter
    public final AutoGeneratedValue.Attribute read(com.google.gson.stream.a aVar) throws IOException {
        if (aVar.F() == JsonToken.f362204j) {
            throw new JsonParseException("");
        }
        JsonToken jsonTokenF = aVar.F();
        JsonToken jsonToken = JsonToken.f362198d;
        if (jsonTokenF != jsonToken) {
            throw new IllegalStateException(com.avito.android.authorization.auto_recovery.phone_confirm.b.e(aVar, com.avito.android.authorization.auto_recovery.phone_confirm.b.k("Expected ", jsonToken, " but was "), " at ", aVar));
        }
        aVar.b();
        String strB = null;
        String strB2 = null;
        String strB3 = null;
        String strB4 = null;
        Boolean boolValueOf = null;
        while (aVar.k()) {
            String strX = aVar.x();
            if (strX != null) {
                switch (strX.hashCode()) {
                    case -980110702:
                        if (!strX.equals("prefix")) {
                            break;
                        } else {
                            strB3 = aVar.B();
                            break;
                        }
                    case -861252683:
                        if (!strX.equals("fieldId")) {
                            break;
                        } else {
                            strB2 = aVar.B();
                            break;
                        }
                    case -393139297:
                        if (!strX.equals("required")) {
                            break;
                        } else {
                            boolValueOf = Boolean.valueOf(aVar.o());
                            break;
                        }
                    case -391205003:
                        if (!strX.equals("postfix")) {
                            break;
                        } else {
                            strB4 = aVar.B();
                            break;
                        }
                    case 3575610:
                        if (!strX.equals("type")) {
                            break;
                        } else {
                            strB = aVar.B();
                            break;
                        }
                }
            }
            aVar.L();
        }
        aVar.g();
        return strB2 == null ? AutoGeneratedValue.Attribute.UnknownAttribute.INSTANCE : kotlin.jvm.internal.L.f(strB, "parameter") ? new AutoGeneratedValue.Attribute.ParameterAttribute(strB2, strB3, strB4, boolValueOf) : AutoGeneratedValue.Attribute.UnknownAttribute.INSTANCE;
    }

    @Override // com.google.gson.TypeAdapter
    public final void write(com.google.gson.stream.c cVar, AutoGeneratedValue.Attribute attribute) throws IOException {
        AutoGeneratedValue.Attribute attribute2 = attribute;
        AutoGeneratedValue.Attribute.ParameterAttribute parameterAttribute = attribute2 instanceof AutoGeneratedValue.Attribute.ParameterAttribute ? (AutoGeneratedValue.Attribute.ParameterAttribute) attribute2 : null;
        if (parameterAttribute == null) {
            cVar.j();
            return;
        }
        cVar.c();
        cVar.h("fieldId");
        cVar.q(parameterAttribute.getParameterId());
        cVar.h("prefix");
        cVar.q(parameterAttribute.getPrefix());
        cVar.h("postfix");
        cVar.q(parameterAttribute.getPostfix());
        cVar.h("required");
        cVar.o(parameterAttribute.getRequired());
        cVar.h("type");
        cVar.q("parameter");
        cVar.g();
    }
}
