package com.avito.android.di.module;

import android.net.Uri;
import com.avito.android.C36135w2;
import com.avito.android.C36168y2;
import com.avito.android.deep_linking.links.DeepLink;
import com.avito.android.remote.model.Action;
import com.avito.android.remote.model.ActionNullable;
import com.avito.android.remote.model.AdvertAction;
import com.avito.android.remote.model.AdvertActions;
import com.avito.android.remote.model.AdvertItemActions;
import com.avito.android.remote.model.AdvertParameters;
import com.avito.android.remote.model.AdvertPrice;
import com.avito.android.remote.model.AdvertStats;
import com.avito.android.remote.model.BeduinV2;
import com.avito.android.remote.model.CaseText;
import com.avito.android.remote.model.Color;
import com.avito.android.remote.model.ConstructorAdvertGalleryItemModel;
import com.avito.android.remote.model.ContactAccessService;
import com.avito.android.remote.model.DimmedImage;
import com.avito.android.remote.model.Error;
import com.avito.android.remote.model.ErrorContainer;
import com.avito.android.remote.model.ExtendedImage;
import com.avito.android.remote.model.GlobalProperties;
import com.avito.android.remote.model.Image;
import com.avito.android.remote.model.ImageUploadResult;
import com.avito.android.remote.model.LinkAction;
import com.avito.android.remote.model.Location;
import com.avito.android.remote.model.NameIdEntity;
import com.avito.android.remote.model.OrderMessage;
import com.avito.android.remote.model.OrderStatus;
import com.avito.android.remote.model.ParametrizedEvent;
import com.avito.android.remote.model.PretendErrorValue;
import com.avito.android.remote.model.PretendResult;
import com.avito.android.remote.model.Radius;
import com.avito.android.remote.model.References;
import com.avito.android.remote.model.SearchParams;
import com.avito.android.remote.model.SearchProperties;
import com.avito.android.remote.model.SerpDisplayType;
import com.avito.android.remote.model.Size;
import com.avito.android.remote.model.SuccessResult;
import com.avito.android.remote.model.SuggestLocation;
import com.avito.android.remote.model.TypedResult;
import com.avito.android.remote.model.UserAdvert;
import com.avito.android.remote.model.branding_gallery.BrandingGalleryItem;
import com.avito.android.remote.model.category_parameters.AutoGeneratedValue;
import com.avito.android.remote.model.category_parameters.Condition;
import com.avito.android.remote.model.category_parameters.Constraint;
import com.avito.android.remote.model.category_parameters.DateTimeParameter;
import com.avito.android.remote.model.category_parameters.PhotoParameter;
import com.avito.android.remote.model.category_parameters.SelectionType;
import com.avito.android.remote.model.credit_broker.CreditBrokerProduct;
import com.avito.android.remote.model.credit_broker.InstallmentsFloatingView;
import com.avito.android.remote.model.installments.InstallmentsSwitcherActionData;
import com.avito.android.remote.model.onboarding.OnboardingItem;
import com.avito.android.remote.model.recommended_sellers.RecommendedSellerElement;
import com.avito.android.remote.model.section.SectionElement;
import com.avito.android.remote.model.section.VipAdvert;
import com.avito.android.remote.model.service_order_widget.ServiceOrderWidget;
import com.avito.android.remote.model.service_subscription.PackageAttribute;
import com.avito.android.remote.model.social.SocialNetwork;
import com.avito.android.remote.model.text.AttributedText;
import com.avito.android.remote.model.vertical_main.FeaturedWidget;
import com.avito.android.remote.model.vertical_main.RubricatorWidget;
import com.avito.android.remote.parse.adapter.ActionNullableDeserializer;
import com.avito.android.remote.parse.adapter.ActionTypeAdapter;
import com.avito.android.remote.parse.adapter.AdvertActionTypeAdapter;
import com.avito.android.remote.parse.adapter.AdvertActionsDeserializer;
import com.avito.android.remote.parse.adapter.AdvertItemActionsTypeAdapter;
import com.avito.android.remote.parse.adapter.AdvertParametersDeserializer;
import com.avito.android.remote.parse.adapter.AdvertPriceAdapter;
import com.avito.android.remote.parse.adapter.AdvertStatsAdapter;
import com.avito.android.remote.parse.adapter.AttributedMessageDeserializer;
import com.avito.android.remote.parse.adapter.AttributedTextAdapter;
import com.avito.android.remote.parse.adapter.BeduinV2Deserializer;
import com.avito.android.remote.parse.adapter.BooleanRuleDeserializer;
import com.avito.android.remote.parse.adapter.BrandingGalleryTypeAdapter;
import com.avito.android.remote.parse.adapter.CaseTextTypeAdapter;
import com.avito.android.remote.parse.adapter.CharSequenceTypeAdapter;
import com.avito.android.remote.parse.adapter.ColorTypeAdapter;
import com.avito.android.remote.parse.adapter.ConditionTypeAdapter;
import com.avito.android.remote.parse.adapter.ConstraintTypeAdapter;
import com.avito.android.remote.parse.adapter.ConstructorAdvertGalleryItemDeserializer;
import com.avito.android.remote.parse.adapter.ContactAccessServiceServiceDeserializer;
import com.avito.android.remote.parse.adapter.CreditBrokerProductTypeAdapter;
import com.avito.android.remote.parse.adapter.DateParameterValueTypeAdapter;
import com.avito.android.remote.parse.adapter.DeepLinkTypeAdapter;
import com.avito.android.remote.parse.adapter.DimmedImageTypeAdapter;
import com.avito.android.remote.parse.adapter.ErrorContainerDeserializer;
import com.avito.android.remote.parse.adapter.ErrorDeserializer;
import com.avito.android.remote.parse.adapter.ExtendedImageAdapter;
import com.avito.android.remote.parse.adapter.FeaturedWidgetDeserializer;
import com.avito.android.remote.parse.adapter.ImageTypeAdapter;
import com.avito.android.remote.parse.adapter.ImageUploadListWrapperDeserializer;
import com.avito.android.remote.parse.adapter.ImageUploadResultsDeserializer;
import com.avito.android.remote.parse.adapter.InstallmentsFloatingViewTypeAdapter;
import com.avito.android.remote.parse.adapter.InstallmentsToggleActionsTypeAdapter;
import com.avito.android.remote.parse.adapter.LinkActionTypeAdapter;
import com.avito.android.remote.parse.adapter.LocationAdapter;
import com.avito.android.remote.parse.adapter.NameIdEntityTypeAdapter;
import com.avito.android.remote.parse.adapter.ObjectsResultDeserializer;
import com.avito.android.remote.parse.adapter.OnboardingItemTypeAdapter;
import com.avito.android.remote.parse.adapter.OrderMessageDeserializer;
import com.avito.android.remote.parse.adapter.OrderStatusDoneDeserializer;
import com.avito.android.remote.parse.adapter.ParameterAttributeTypeAdapter;
import com.avito.android.remote.parse.adapter.ParametrizedEventTypeAdapter;
import com.avito.android.remote.parse.adapter.PretendResultTypeAdapter;
import com.avito.android.remote.parse.adapter.PretendTypeAdapter;
import com.avito.android.remote.parse.adapter.PriceRuleValueDeserializer;
import com.avito.android.remote.parse.adapter.RadiusAdapter;
import com.avito.android.remote.parse.adapter.RecommendedSellerTypeAdapter;
import com.avito.android.remote.parse.adapter.ReferencesTypeAdapter;
import com.avito.android.remote.parse.adapter.RubricatorWidgetTypeDeserializer;
import com.avito.android.remote.parse.adapter.SearchParamsDeserializer;
import com.avito.android.remote.parse.adapter.SectionElementTypeAdapter;
import com.avito.android.remote.parse.adapter.SelectionTypeDeserializer;
import com.avito.android.remote.parse.adapter.SerpResultDisplayTypeAdapter;
import com.avito.android.remote.parse.adapter.ServiceOrderWidgetDeserializer;
import com.avito.android.remote.parse.adapter.SizeTypeAdapter;
import com.avito.android.remote.parse.adapter.SocialNetworkTypeAdapter;
import com.avito.android.remote.parse.adapter.SubscriptionPackageDeserializer;
import com.avito.android.remote.parse.adapter.SuccessResultDeserializer;
import com.avito.android.remote.parse.adapter.SuggestLocationAdapter;
import com.avito.android.remote.parse.adapter.TypedResultDeserializer;
import com.avito.android.remote.parse.adapter.UriTypeAdapter;
import com.avito.android.remote.parse.adapter.UserAdvertStatusDeserializer;
import com.avito.android.remote.parse.adapter.VipAdvertTypeAdapter;
import com.avito.android.saved_searches.model.SearchSubscription;
import com.avito.android.saved_searches.parse.adapter.SearchSubscriptionDeserializer;
import hD.C40806a;
import hD.C40808c;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.inject.Provider;
import kotlin.Metadata;
import kotlin.jvm.internal.C42822w;
import lD.C43619c;

/* compiled from: CoreJsonModule_ProvideCommonTypeAdaptersFactory.kt */
@Metadata(d1 = {"\u0000\u0018\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0010\"\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\u0018\u00002\u0013\u0012\u000f\u0012\r\u0012\u0004\u0012\u00020\u00030\u0002¢\u0006\u0002\b\u00040\u0001:\u0001\u0005¨\u0006\u0006"}, d2 = {"Lcom/avito/android/di/module/g3;", "Ldagger/internal/h;", "", "Lcom/avito/android/util/X5;", "LX41/o;", "a", "_avito_network_impl"}, k = 1, mv = {1, 9, 0}, xi = 48)
/* renamed from: com.avito.android.di.module.g3, reason: case insensitive filesystem */
/* loaded from: classes13.dex */
public final class C30047g3 implements dagger.internal.h<Set<com.avito.android.util.X5>> {

    /* renamed from: g, reason: collision with root package name */
    @Y61.k
    public static final a f144296g = new a(null);

    /* renamed from: a, reason: collision with root package name */
    @Y61.k
    public final C43619c f144297a;

    /* renamed from: b, reason: collision with root package name */
    @Y61.k
    public final dagger.internal.f f144298b;

    /* renamed from: c, reason: collision with root package name */
    @Y61.k
    public final C40808c f144299c;

    /* renamed from: d, reason: collision with root package name */
    @Y61.k
    public final com.avito.android.S f144300d;

    /* renamed from: e, reason: collision with root package name */
    @Y61.k
    public final C36168y2 f144301e;

    /* renamed from: f, reason: collision with root package name */
    @Y61.k
    public final Provider<TypedResultDeserializer> f144302f;

    /* compiled from: CoreJsonModule_ProvideCommonTypeAdaptersFactory.kt */
    @Metadata(d1 = {"\u0000\f\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0003\b\u0086\u0003\u0018\u00002\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0002\u0010\u0003¨\u0006\u0004"}, d2 = {"Lcom/avito/android/di/module/g3$a;", "", "<init>", "()V", "_avito_network_impl"}, k = 1, mv = {1, 9, 0}, xi = 48)
    /* renamed from: com.avito.android.di.module.g3$a */
    public static final class a {
        public /* synthetic */ a(C42822w c42822w) {
            this();
        }

        public a() {
        }
    }

    public C30047g3(@Y61.k C43619c c43619c, @Y61.k dagger.internal.f fVar, @Y61.k C40808c c40808c, @Y61.k com.avito.android.S s5, @Y61.k C36168y2 c36168y2, @Y61.k Provider provider) {
        this.f144297a = c43619c;
        this.f144298b = fVar;
        this.f144299c = c40808c;
        this.f144300d = s5;
        this.f144301e = c36168y2;
        this.f144302f = provider;
    }

    @Override // javax.inject.Provider
    public final Object get() {
        this.f144297a.get();
        com.avito.android.deep_linking.x xVar = (com.avito.android.deep_linking.x) this.f144298b.get();
        C40806a c40806a = (C40806a) this.f144299c.get();
        this.f144300d.get();
        C36135w2 c36135w2 = (C36135w2) this.f144301e.get();
        TypedResultDeserializer typedResultDeserializer = this.f144302f.get();
        f144296g.getClass();
        int i12 = C30025e3.f144277a;
        LinkedHashSet linkedHashSet = new LinkedHashSet();
        linkedHashSet.add(new com.avito.android.util.X5(TypedResult.class, typedResultDeserializer));
        linkedHashSet.add(new com.avito.android.util.X5(Uri.class, new UriTypeAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(AttributedText.class, new AttributedTextAdapter(null, 1, null)));
        linkedHashSet.add(new com.avito.android.util.X5(AttributedText.class, new AttributedTextAdapter(null, 1, null)));
        linkedHashSet.add(new com.avito.android.util.X5(AdvertStats.class, new AdvertStatsAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(AdvertParameters.class, new AdvertParametersDeserializer()));
        linkedHashSet.add(new com.avito.android.util.X5(Image.class, new ImageTypeAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(DimmedImage.class, new DimmedImageTypeAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(ParametrizedEvent.class, new ParametrizedEventTypeAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(LinkAction.class, new LinkActionTypeAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(DeepLink.class, new DeepLinkTypeAdapter(xVar)));
        linkedHashSet.add(new com.avito.android.util.X5(Action.class, new ActionTypeAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(ActionNullable.class, new ActionNullableDeserializer()));
        linkedHashSet.add(new com.avito.android.util.X5(CharSequence.class, new CharSequenceTypeAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(AdvertAction.class, new AdvertActionTypeAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(AdvertActions.class, new AdvertActionsDeserializer()));
        linkedHashSet.add(new com.avito.android.util.X5(PretendResult.class, new PretendTypeAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(ImageUploadResult.class, new ImageUploadResultsDeserializer()));
        linkedHashSet.add(new com.avito.android.util.X5(PhotoParameter.ImageUploadListWrapper.class, new ImageUploadListWrapperDeserializer()));
        linkedHashSet.add(new com.avito.android.util.X5(PretendErrorValue.class, new PretendResultTypeAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(PretendErrorValue.ObjectsMessages.class, new ObjectsResultDeserializer()));
        linkedHashSet.add(new com.avito.android.util.X5(PretendErrorValue.AttributedMessage.class, new AttributedMessageDeserializer()));
        linkedHashSet.add(new com.avito.android.util.X5(DateTimeParameter.Value.class, new DateParameterValueTypeAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(SocialNetwork.class, new SocialNetworkTypeAdapter(c40806a)));
        linkedHashSet.add(new com.avito.android.util.X5(ConstructorAdvertGalleryItemModel.class, new ConstructorAdvertGalleryItemDeserializer()));
        linkedHashSet.add(new com.avito.android.util.X5(AdvertPrice.class, new AdvertPriceAdapter(new AttributedTextAdapter(null, 1, null))));
        linkedHashSet.add(new com.avito.android.util.X5(References.class, new ReferencesTypeAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(CaseText.class, new CaseTextTypeAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(SectionElement.class, new SectionElementTypeAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(VipAdvert.class, new VipAdvertTypeAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(NameIdEntity.class, new NameIdEntityTypeAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(UserAdvert.Status.class, new UserAdvertStatusDeserializer()));
        linkedHashSet.add(new com.avito.android.util.X5(Color.class, new ColorTypeAdapter(null, 1, null)));
        linkedHashSet.add(new com.avito.android.util.X5(Constraint.class, new ConstraintTypeAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(Condition.class, new ConditionTypeAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(Location.class, new LocationAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(Radius.class, new RadiusAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(SuggestLocation.class, new SuggestLocationAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(SerpDisplayType.class, new SerpResultDisplayTypeAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(SelectionType.class, new SelectionTypeDeserializer()));
        linkedHashSet.add(new com.avito.android.util.X5(SearchProperties.BooleanRule.class, new BooleanRuleDeserializer()));
        linkedHashSet.add(new com.avito.android.util.X5(GlobalProperties.PriceRule.Value.class, new PriceRuleValueDeserializer()));
        linkedHashSet.add(new com.avito.android.util.X5(OrderMessage.class, new OrderMessageDeserializer()));
        linkedHashSet.add(new com.avito.android.util.X5(FeaturedWidget.class, new FeaturedWidgetDeserializer(c36135w2, new AttributedTextAdapter(null, 1, null))));
        linkedHashSet.add(new com.avito.android.util.X5(OrderStatus.Done.class, new OrderStatusDoneDeserializer()));
        linkedHashSet.add(new com.avito.android.util.X5(SuccessResult.class, new SuccessResultDeserializer()));
        linkedHashSet.add(new com.avito.android.util.X5(SearchParams.class, new SearchParamsDeserializer()));
        linkedHashSet.add(new com.avito.android.util.X5(SearchSubscription.class, new SearchSubscriptionDeserializer()));
        linkedHashSet.add(new com.avito.android.util.X5(ErrorContainer.class, new ErrorContainerDeserializer()));
        linkedHashSet.add(new com.avito.android.util.X5(Error.class, new ErrorDeserializer()));
        linkedHashSet.add(new com.avito.android.util.X5(ContactAccessService.Service.class, new ContactAccessServiceServiceDeserializer()));
        linkedHashSet.add(new com.avito.android.util.X5(ExtendedImage.class, new ExtendedImageAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(AdvertItemActions.class, new AdvertItemActionsTypeAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(RecommendedSellerElement.class, new RecommendedSellerTypeAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(PackageAttribute.class, new SubscriptionPackageDeserializer()));
        linkedHashSet.add(new com.avito.android.util.X5(RubricatorWidget.RubricatorWidgetType.class, new RubricatorWidgetTypeDeserializer()));
        linkedHashSet.add(new com.avito.android.util.X5(AutoGeneratedValue.Attribute.class, new ParameterAttributeTypeAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(Size.class, new SizeTypeAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(CreditBrokerProduct.class, new CreditBrokerProductTypeAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(OnboardingItem.class, new OnboardingItemTypeAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(InstallmentsSwitcherActionData.class, new InstallmentsToggleActionsTypeAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(InstallmentsFloatingView.class, new InstallmentsFloatingViewTypeAdapter()));
        linkedHashSet.add(new com.avito.android.util.X5(ServiceOrderWidget.class, new ServiceOrderWidgetDeserializer()));
        linkedHashSet.add(new com.avito.android.util.X5(BeduinV2.class, new BeduinV2Deserializer()));
        linkedHashSet.add(new com.avito.android.util.X5(BrandingGalleryItem.class, new BrandingGalleryTypeAdapter()));
        return linkedHashSet;
    }
}
