package nf;

import Y41.p;
import Y61.k;
import android.text.Editable;
import androidx.compose.runtime.internal.P;
import com.avito.android.autogenerated_value.CannotProcessAttribute;
import com.avito.android.remote.model.category_parameters.AutoGeneratedValue;
import com.avito.android.remote.model.category_parameters.ParametersTree;
import com.avito.android.remote.model.category_parameters.WithAutogeneratedValue;
import com.avito.android.remote.model.category_parameters.base.ParameterSlot;
import com.avito.android.util.C;
import com.avito.android.util.D5;
import com.avito.android.validation.InterfaceC35998b;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import kotlin.Metadata;
import kotlin.collections.C42745f0;
import kotlin.collections.C42784z0;
import kotlin.jvm.internal.L;
import kotlin.jvm.internal.s0;

/* compiled from: AutogeneratedValueInteractor.kt */
@P
@s0
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0000\b\u0007\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lnf/c;", "Lnf/a;", "_avito-discouraged_avito-libs_publish-common"}, k = 1, mv = {1, 9, 0}, xi = 48)
/* loaded from: classes11.dex */
public final class c implements InterfaceC44415a {

    /* renamed from: a, reason: collision with root package name */
    @k
    public final InterfaceC35998b f419110a;

    /* renamed from: b, reason: collision with root package name */
    @k
    public final C f419111b;

    /* renamed from: c, reason: collision with root package name */
    @k
    public final ParametersTree f419112c;

    /* renamed from: d, reason: collision with root package name */
    @k
    public final Set<String> f419113d;

    /* JADX WARN: Multi-variable type inference failed */
    /* JADX WARN: Type inference failed for: r0v0, types: [kotlin.collections.z0] */
    /* JADX WARN: Type inference failed for: r0v1 */
    /* JADX WARN: Type inference failed for: r0v3, types: [java.util.ArrayList] */
    public c(@k InterfaceC35998b interfaceC35998b, @k C c12, @k ParametersTree parametersTree) {
        ?? arrayList;
        Map<String, AutoGeneratedValue.Attribute> attributes;
        Collection<AutoGeneratedValue.Attribute> collectionValues;
        this.f419110a = interfaceC35998b;
        this.f419111b = c12;
        this.f419112c = parametersTree;
        ArrayList arrayList2 = new ArrayList();
        for (ParameterSlot parameterSlot : parametersTree) {
            if (parameterSlot instanceof WithAutogeneratedValue) {
                arrayList2.add(parameterSlot);
            }
        }
        ArrayList arrayList3 = new ArrayList();
        Iterator it = arrayList2.iterator();
        while (it.hasNext()) {
            AutoGeneratedValue autogeneratedValue = ((WithAutogeneratedValue) it.next()).getAutogeneratedValue();
            if (autogeneratedValue == null || (attributes = autogeneratedValue.getAttributes()) == null || (collectionValues = attributes.values()) == null) {
                arrayList = C42784z0.f406748b;
            } else {
                arrayList = new ArrayList();
                for (AutoGeneratedValue.Attribute attribute : collectionValues) {
                    String parameterId = attribute instanceof AutoGeneratedValue.Attribute.ParameterAttribute ? ((AutoGeneratedValue.Attribute.ParameterAttribute) attribute).getParameterId() : null;
                    if (parameterId != null) {
                        arrayList.add(parameterId);
                    }
                }
            }
            C42745f0.h((Iterable) arrayList, arrayList3);
        }
        this.f419113d = C42745f0.P0(arrayList3);
    }

    @Override // nf.InterfaceC44415a
    public final void a(@k p pVar, @k String str) {
        Editable editableNewEditable;
        Map<String, AutoGeneratedValue.Attribute> attributes;
        AutoGeneratedValue autogeneratedValue;
        String pattern;
        Map<String, AutoGeneratedValue.Attribute> attributes2;
        Collection<AutoGeneratedValue.Attribute> collectionValues;
        if (this.f419113d.contains(str)) {
            ArrayList arrayList = new ArrayList();
            Iterator<ParameterSlot> it = this.f419112c.iterator();
            while (true) {
                Object obj = null;
                if (!it.hasNext()) {
                    break;
                }
                ParameterSlot next = it.next();
                if (next instanceof WithAutogeneratedValue) {
                    AutoGeneratedValue autogeneratedValue2 = ((WithAutogeneratedValue) next).getAutogeneratedValue();
                    if (autogeneratedValue2 != null && (attributes2 = autogeneratedValue2.getAttributes()) != null && (collectionValues = attributes2.values()) != null) {
                        Iterator<T> it2 = collectionValues.iterator();
                        while (true) {
                            if (!it2.hasNext()) {
                                break;
                            }
                            Object next2 = it2.next();
                            AutoGeneratedValue.Attribute attribute = (AutoGeneratedValue.Attribute) next2;
                            if ((attribute instanceof AutoGeneratedValue.Attribute.ParameterAttribute) && L.f(((AutoGeneratedValue.Attribute.ParameterAttribute) attribute).getParameterId(), str)) {
                                obj = next2;
                                break;
                            }
                        }
                        obj = (AutoGeneratedValue.Attribute) obj;
                    }
                    if (obj != null) {
                        arrayList.add(next);
                    }
                }
            }
            Iterator it3 = arrayList.iterator();
            while (it3.hasNext()) {
                WithAutogeneratedValue withAutogeneratedValue = (WithAutogeneratedValue) it3.next();
                AutoGeneratedValue autogeneratedValue3 = withAutogeneratedValue.getAutogeneratedValue();
                if (autogeneratedValue3 == null || (attributes = autogeneratedValue3.getAttributes()) == null || (autogeneratedValue = withAutogeneratedValue.getAutogeneratedValue()) == null || (pattern = autogeneratedValue.getPattern()) == null) {
                    editableNewEditable = null;
                } else {
                    editableNewEditable = Editable.Factory.getInstance().newEditable(pattern);
                    try {
                        new D5();
                        D5.a(editableNewEditable, new C44416b(attributes, this));
                    } catch (CannotProcessAttribute unused) {
                    }
                }
                if (editableNewEditable != null) {
                    pVar.invoke(withAutogeneratedValue.getId(), editableNewEditable);
                }
            }
        }
    }
}
