package nf;

import Y61.k;
import com.avito.android.remote.model.category_parameters.AutoGeneratedValue;
import com.avito.android.util.D5;
import java.util.Map;
import kotlin.Metadata;

/* compiled from: AutogeneratedValueInteractor.kt */
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0000\b\n\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lnf/b;", "Lcom/avito/android/util/D5$a;", "_avito-discouraged_avito-libs_publish-common"}, k = 1, mv = {1, 9, 0}, xi = 48)
/* renamed from: nf.b, reason: case insensitive filesystem */
/* loaded from: classes11.dex */
public final class C44416b implements D5.a {

    /* renamed from: a, reason: collision with root package name */
    @k
    public final e f419108a;

    /* renamed from: b, reason: collision with root package name */
    public final /* synthetic */ Map<String, AutoGeneratedValue.Attribute> f419109b;

    /* JADX WARN: Multi-variable type inference failed */
    public C44416b(Map<String, ? extends AutoGeneratedValue.Attribute> map, c cVar) {
        this.f419109b = map;
        this.f419108a = new e(map, cVar.f419112c, cVar.f419110a, cVar.f419111b);
    }

    /* JADX WARN: Removed duplicated region for block: B:36:0x0093  */
    @Override // com.avito.android.util.D5.a
    /*
        Code decompiled incorrectly, please refer to instructions dump.
        To view partially-correct add '--show-bad-code' argument
    */
    public final void a(@Y61.k android.text.Editable r12, @Y61.k java.lang.String r13, int r14, int r15) throws com.avito.android.autogenerated_value.CannotProcessAttribute {
        /*
            Method dump skipped, instructions count: 243
            To view this dump add '--comments-level debug' option
        */
        throw new UnsupportedOperationException("Method not decompiled: nf.C44416b.a(android.text.Editable, java.lang.String, int, int):void");
    }
}
