package nf;

import com.avito.android.remote.model.category_parameters.AutoGeneratedValue;
import com.avito.android.remote.model.category_parameters.AutoGeneratedValue.Attribute;
import kotlin.Metadata;

/* compiled from: AutogeneratedValueVisitor.kt */
@Metadata(d1 = {"\u0000\u0010\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0000\n\u0000\bf\u0018\u0000*\b\b\u0000\u0010\u0002*\u00020\u00012\u00020\u0003¨\u0006\u0004"}, d2 = {"Lnf/d;", "Lcom/avito/android/remote/model/category_parameters/AutoGeneratedValue$Attribute;", "T", "", "_avito-discouraged_avito-libs_publish-common"}, k = 1, mv = {1, 9, 0}, xi = 48)
/* loaded from: classes11.dex */
public interface d<T extends AutoGeneratedValue.Attribute> {
}
