package nf;

import Y61.k;
import androidx.compose.runtime.internal.P;
import com.avito.android.remote.model.category_parameters.AutoGeneratedValue;
import com.avito.android.remote.model.category_parameters.ParametersTree;
import com.avito.android.remote.model.category_parameters.base.CategoryParameter;
import com.avito.android.remote.model.category_parameters.base.ParameterSlot;
import com.avito.android.util.C;
import com.avito.android.util.V2;
import com.avito.android.validation.InterfaceC35998b;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.Map;
import kotlin.Metadata;
import kotlin.jvm.internal.s0;

/* compiled from: ParameterAttributesVisitor.kt */
@P
@s0
@Metadata(d1 = {"\u0000\u000e\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0000\b\u0007\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001¨\u0006\u0003"}, d2 = {"Lnf/e;", "Lnf/d;", "Lcom/avito/android/remote/model/category_parameters/AutoGeneratedValue$Attribute$ParameterAttribute;", "_avito-discouraged_avito-libs_publish-common"}, k = 1, mv = {1, 9, 0}, xi = 48)
/* loaded from: classes11.dex */
public final class e implements d<AutoGeneratedValue.Attribute.ParameterAttribute> {

    /* renamed from: a, reason: collision with root package name */
    @k
    public final ParametersTree f419114a;

    /* renamed from: b, reason: collision with root package name */
    @k
    public final InterfaceC35998b f419115b;

    /* renamed from: c, reason: collision with root package name */
    @k
    public final C f419116c;

    /* renamed from: d, reason: collision with root package name */
    @k
    public final LinkedHashMap f419117d;

    /* renamed from: e, reason: collision with root package name */
    @k
    public final ArrayList f419118e;

    /* renamed from: f, reason: collision with root package name */
    @k
    public final LinkedHashMap f419119f;

    public e(@k Map<String, ? extends AutoGeneratedValue.Attribute> map, @k ParametersTree parametersTree, @k InterfaceC35998b interfaceC35998b, @k C c12) {
        this.f419114a = parametersTree;
        this.f419115b = interfaceC35998b;
        this.f419116c = c12;
        LinkedHashMap linkedHashMap = new LinkedHashMap();
        for (Map.Entry<String, ? extends AutoGeneratedValue.Attribute> entry : map.entrySet()) {
            AutoGeneratedValue.Attribute value = entry.getValue();
            AutoGeneratedValue.Attribute.ParameterAttribute parameterAttribute = value instanceof AutoGeneratedValue.Attribute.ParameterAttribute ? (AutoGeneratedValue.Attribute.ParameterAttribute) value : null;
            if (parameterAttribute != null) {
            }
        }
        this.f419117d = linkedHashMap;
        Collection collectionValues = linkedHashMap.values();
        ArrayList<ParameterSlot> arrayList = new ArrayList();
        Iterator it = collectionValues.iterator();
        while (it.hasNext()) {
            ParameterSlot parameterSlotFindParameter = this.f419114a.findParameter(((AutoGeneratedValue.Attribute.ParameterAttribute) it.next()).getParameterId());
            if (parameterSlotFindParameter != null) {
                arrayList.add(parameterSlotFindParameter);
            }
        }
        this.f419118e = arrayList;
        LinkedHashMap linkedHashMap2 = new LinkedHashMap();
        for (ParameterSlot parameterSlot : arrayList) {
            linkedHashMap2.put(parameterSlot.getId(), a(parameterSlot));
        }
        this.f419119f = linkedHashMap2;
    }

    public final String a(ParameterSlot parameterSlot) {
        if (parameterSlot instanceof CategoryParameter) {
            return this.f419115b.a((CategoryParameter) parameterSlot);
        }
        this.f419116c.getF125491k().getClass();
        V2.f318762a.e(parameterSlot.toString(), null);
        return null;
    }
}
