package nf;

import Y41.p;
import Y61.k;
import kotlin.Metadata;

/* compiled from: AutogeneratedValueInteractor.kt */
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bf\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lnf/a;", "", "_avito-discouraged_avito-libs_publish-common"}, k = 1, mv = {1, 9, 0}, xi = 48)
/* renamed from: nf.a, reason: case insensitive filesystem */
/* loaded from: classes11.dex */
public interface InterfaceC44415a {
    void a(@k p pVar, @k String str);
}
