package com.avito.android.validation;

import java.util.LinkedHashMap;
import kotlin.Metadata;

/* compiled from: ParametersListInteractor.kt */
@Metadata(d1 = {"\u0000\u0014\n\u0002\u0010\u000e\n\u0000\n\u0002\u0010\r\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0003\u0010\u0007\u001a\u00020\u00042\u0006\u0010\u0001\u001a\u00020\u00002\b\u0010\u0003\u001a\u0004\u0018\u00010\u0002H\n¢\u0006\u0004\b\u0005\u0010\u0006"}, d2 = {"", "autogeneratedParamId", "", "generatedValue", "Lkotlin/G0;", "invoke", "(Ljava/lang/String;Ljava/lang/CharSequence;)V", "<anonymous>"}, k = 3, mv = {1, 9, 0})
/* renamed from: com.avito.android.validation.t, reason: case insensitive filesystem */
/* loaded from: classes5.dex */
final class C36033t extends kotlin.jvm.internal.N implements Y41.p<String, CharSequence, kotlin.G0> {

    /* renamed from: l, reason: collision with root package name */
    public final /* synthetic */ C36045z f319420l;

    /* renamed from: m, reason: collision with root package name */
    public final /* synthetic */ LinkedHashMap f319421m;

    /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
    public C36033t(C36045z c36045z, LinkedHashMap linkedHashMap) {
        super(2);
        this.f319420l = c36045z;
        this.f319421m = linkedHashMap;
    }

    @Override // Y41.p
    public final kotlin.G0 invoke(String str, CharSequence charSequence) {
        String str2 = str;
        CharSequence charSequence2 = charSequence;
        this.f319420l.j(str2, charSequence2 != null ? charSequence2.toString() : null, null);
        this.f319421m.put(str2, String.valueOf(charSequence2));
        return kotlin.G0.f406611a;
    }
}
