package com.avito.android.remote.model;

import K51.c;
import Y61.k;
import android.os.Parcel;
import com.avito.android.util.J3;
import java.util.List;
import kotlin.G;
import kotlin.Metadata;
import kotlin.collections.C42784z0;
import kotlin.jvm.internal.s0;

/* compiled from: SerpElementResult.kt */
@s0
@Metadata(d1 = {"\u0000*\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0010 \n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\b\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0003\bÆ\u0002\u0018\u00002\u000e\u0012\n\u0012\b\u0012\u0004\u0012\u00020\u00030\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0004\u0010\u0005J\u001d\u0010\b\u001a\b\u0012\u0004\u0012\u00020\u00030\u00022\u0006\u0010\u0007\u001a\u00020\u0006H\u0016¢\u0006\u0004\b\b\u0010\tJ)\u0010\r\u001a\u00020\f*\b\u0012\u0004\u0012\u00020\u00030\u00022\u0006\u0010\u0007\u001a\u00020\u00062\u0006\u0010\u000b\u001a\u00020\nH\u0016¢\u0006\u0004\b\r\u0010\u000e¨\u0006\u000f"}, d2 = {"Lcom/avito/android/remote/model/SerpElementOptimizedParceler;", "LK51/c;", "", "Lcom/avito/android/remote/model/SerpElement;", "<init>", "()V", "Landroid/os/Parcel;", "parcel", "create", "(Landroid/os/Parcel;)Ljava/util/List;", "", "flags", "Lkotlin/G0;", "write", "(Ljava/util/List;Landroid/os/Parcel;I)V", "_avito-discouraged_avito-api_search"}, k = 1, mv = {1, 9, 0}, xi = 48)
/* loaded from: classes17.dex */
public final class SerpElementOptimizedParceler implements c<List<? extends SerpElement>> {

    @k
    public static final SerpElementOptimizedParceler INSTANCE = new SerpElementOptimizedParceler();

    private SerpElementOptimizedParceler() {
    }

    @k
    public List<SerpElement> create(@k Parcel parcel) {
        List<SerpElement> listA = J3.a(parcel, SerpElement.class.getClassLoader());
        return listA == null ? C42784z0.f406748b : listA;
    }

    @k
    public List<SerpElement>[] newArray(int i12) {
        throw new G("Generated by Android Extensions automatically");
    }

    public void write(@k List<? extends SerpElement> list, @k Parcel parcel, int i12) {
        J3.e(list, parcel, i12);
    }
}
